### ISSUE TITLE
Add creation of custom fields on Task & Job

### ISSUE THREAD

**Issue by Yacobolo** [Yacobolo/factryflow#67]
We need to be able to create custom fields i order to add item_first_part, item_second_part, item_third_part

**Comment by Yacobolo** [comment]
what jpi did was have hardcode custom_fields like customfieldvalue1, customfieldvalue2 etc. Lets see if there is a better way

**Comment by mjducut-oe** [comment]
**Steps:**
- [x] Created models: custom_field and custom_field_value.
- [x] Create initial rest api methods and custom fields. 
- [x] Test link to other model using GenericRelation 
- [x] Add validations/serializers 
- [ ] Add tests
